openapi: 3.0.0
info:
  description: Personal website API docs
  version: "0.1.0"
  title: porkbrain

paths:
    /api/posts:
        description: >-
            APIs for working with generic posts. Posts are displayed at
            homepage. Other logic might use these posts to include them in
            whatever it is doing. Post is kind of like quote or reference.
            The purpose is to have something that holds a heading and some short
            description, have optionally a link associated with it, and
            reusable.

            Since it's displayed at homepage, there will be an overview of
            what's being posted to the website.
        post:
            summary: Creates a new post
            operationId: createPost
            security:
              - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/NewPost'
            responses:
                '201':
                    description: Successfully created
                '403':
                    description: Wrong token
                '422':
                    description: Some fields are missing or in wrong format
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/unstructured:
        description: >-
            API which supports text parsing. It was designed to work well with
            email integration. It will attempt to find a url which is alone on a
            line and set that as post url. It will trim the white spaces from
            the rest of the body, remove the url, and treat that as description.
        post:
            summary: Creates a new post from unstructured payload
            operationId: createPostUnstructured
            security:
              - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EmailPayload'
            responses:
                '201':
                    description: Successfully created
                '400':
                    description: Both subject and body is empty
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '403':
                    description: Wrong token
                '422':
                    description: Some fields are in wrong format
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
        type: http
        scheme: bearer
  schemas:
    NewPost:
        type: object
        required:
            - heading
            - description
        properties:
            heading:
                type: string
                description: >-
                    Few words that summarize the post. If the post is a
                    reference to a blog post, it can be the title of the blog
                    post.
            description:
                type: string
            url:
                type: string
    EmailPayload:
        type: object
        properties:
            subject:
                type: string
            body:
                type: string
    Error:
        type: object
        required:
            - message
        properties:
            message:
                type: string
