version: '3.7'

volumes:
    porkbrain_postgres:

services:
    porkbrain:
        container_name: porkbrain
        depends_on:
            - porkbrain-postgres
        build: .
        ports:
            - "4000:4000"
        environment:
            - DB_HOST=porkbrain-postgres
        command:
            - ./run.sh
        volumes:
            - type: bind
              source: .
              target: /app
    porkbrain-postgres:
        container_name: porkbrain-postgres
        image: postgres
        volumes:
            - porkbrain_postgres:/var/lib/postgresql/data
