version: '3.7'

networks:
  server:
    name: porkbrain-net

volumes:
    postgres:

services:
    porkbrain:
        container_name: porkbrain
        depends_on:
            - porkbrain-postgres
        build: .
        ports:
            - "4000:4000"
        environment:
            - DB_HOST=porkbrain-postgres
        command:
            - ./run.sh
        networks:
            - server
        volumes:
            - type: bind
              source: .
              target: /app
    porkbrain-postgres:
        container_name: porkbrain-postgres
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - server
        environment:
            # we don't need to auth locally
            POSTGRES_HOST_AUTH_METHOD: trust
